services:
    webapp:
        container_name: "ampt-ci"

        build:
            context: .
            dockerfile: Dockerfile

        ports:
            - 80:80

        volumes:
            - ./service:/var/www:rw

        restart: always